# Package definition for k9s

package_name: k9s
github_repo: derailed/k9s
license: Apache-2.0
artifact_format: tar.gz
description: "Kubernetes CLI to manage your clusters in style"
license: Apache-2.0

# Build for all Debian suites and all supported architectures.
